print('first tries with python')
print('what type is 1? ', type(1))
print('what type is hola? ', type('hola'))
print('what type is [1,2,3]? ', type([1,2,3]))
print('what type is {a:1, b:2}? ', type({'a':1, 'b':2}))
print('what type is {1,2,3} ? ', type({1,2,3}))
print('what type is True ? ', type(True))
print('what type is None? ', type(None))
print('what type is 1.0? ', type(1.0))
